/**
 * deploy.js — Deploy PrivateToken to Polygon Amoy
 *
 * Deployment order:
 *   1. PoseidonT4  — on-chain Poseidon hasher (for withdrawal verification)
 *   2. Verifier    — Groth16 proof verifier (auto-generated by snarkjs)
 *   3. PrivateToken(verifier, poseidonT4)
 *
 * Run:
 *   npm run deploy:amoy
 *
 * Requires:
 *   .env with PRIVATE_KEY and AMOY_RPC_URL
 *   contracts generated: npm run export:contracts && npm run compile:contracts
 */

const hre = require("hardhat");
const { poseidonContract } = require("circomlibjs");
const fs  = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  console.log("Account balance:", hre.ethers.formatEther(
    await hre.ethers.provider.getBalance(deployer.address)
  ), "MATIC\n");

  // ---- 1. Deploy PoseidonT4 from raw bytecode (circomlibjs generates bytecode, not Solidity) ----
  console.log("==> Deploying PoseidonT4...");
  const poseidonBytecode = poseidonContract.createCode(3); // 3 inputs: balance, secret, nonce
  // Define ABI manually — circomlibjs ABI is not compatible with ethers v6
  const poseidonAbi = [
    {
      inputs: [{ internalType: "uint256[3]", name: "inputs", type: "uint256[3]" }],
      name: "poseidon",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "pure",
      type: "function",
    },
  ];
  const PoseidonFactory  = new hre.ethers.ContractFactory(poseidonAbi, poseidonBytecode, deployer);
  const poseidon         = await PoseidonFactory.deploy();
  await poseidon.waitForDeployment();
  const poseidonAddr = await poseidon.getAddress();
  console.log("    PoseidonT4:", poseidonAddr);

  // ---- 2. Deploy Verifier ----
  console.log("\n==> Deploying Groth16Verifier...");
  const Verifier = await hre.ethers.getContractFactory("Groth16Verifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddr = await verifier.getAddress();
  console.log("    Groth16Verifier:", verifierAddr);

  // ---- 3. Deploy PrivateToken ----
  console.log("\n==> Deploying PrivateToken...");
  const PrivateToken = await hre.ethers.getContractFactory("PrivateToken");
  const token        = await PrivateToken.deploy(verifierAddr, poseidonAddr);
  await token.waitForDeployment();
  const tokenAddr = await token.getAddress();
  console.log("    PrivateToken:", tokenAddr);

  // ---- Save deployment info ----
  const deployment = {
    network:      hre.network.name,
    chainId:      (await hre.ethers.provider.getNetwork()).chainId.toString(),
    deployer:     deployer.address,
    deployedAt:   new Date().toISOString(),
    contracts: {
      PoseidonT4:   poseidonAddr,
      Verifier:     verifierAddr,
      PrivateToken: tokenAddr,
    },
  };

  const outPath = path.join(__dirname, "../build/deployment.json");
  fs.writeFileSync(outPath, JSON.stringify(deployment, null, 2));
  console.log("\n==> Deployment saved to build/deployment.json");
  console.log(JSON.stringify(deployment.contracts, null, 2));

  console.log(`\nVerify on explorer:`);
  console.log(`  https://amoy.polygonscan.com/address/${tokenAddr}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
